### ISSUE TITLE
[FEAT]: Add Dark mode 

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#8] opened 2023-10-19 10:25 UTC
Add the dark mode using the toggle switch button. 
Make sure all the text must be visible in both modes.
here is the example
![image](https://github.com/devjainofficial/Weather-app/assets/69387311/d76a347f-45d9-4100-8858-f9a420654318)

**Comment by AniketNS** [comment] 2023-10-19 10:34
Hello @devjainofficial, Can you please assign this issue to me?

**Comment by DeepRahangdale** [comment] 2023-10-19 17:00
if the issue is still not solved would love to work on this!!

**Comment by devjainofficial** [comment] 2023-10-20 02:41
I assigned it to @AniketNS and @DeepRahangdale both of you, whoever completes it first and whoever's code is more relevant I'll merge his pull request.
Remember to share the screenshot of both versions (dark and light) of the website.

**Closed** 2023-10-26 08:49 UTC
Labels: enhancement, hacktoberfest, urgent, opened
